#!/bin/sh

# clone.sh is a utility script to help maintain a second local McSync
# folder in order to build and test the network capabilities locally.

# It builds McSync and then copies its complete root folder to a sibling
# folder, which than has a "2" added to its name.

# We need the most recent build
./compile -b develop

# Find the McSync directory and make sure to follow symbolic links
MC_SYNC_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $MC_SYNC_DIR
cd ..

# Look for the clone McSync, create or clean it
if [ ! -d "${MC_SYNC_DIR}2" ]; then
    mkdir "${MC_SYNC_DIR}2"
else
    rm -r "${MC_SYNC_DIR}2"/*
fi

# Copy all the contents
cp -r $MC_SYNC_DIR/* "${MC_SYNC_DIR}2"