#!/bin/sh

# Clone.sh is a utility script to help maintain a second local McSync
# folder in order to build and test the network capabilities locally.

# It creates a second folder with the same name as the one the script
# is stored in, adds a "2" to its name and copies all contents form the
# first one into it. It also works if the second folder already exists.

# We need the most recent build
make

# Find the McSync directory and make sure to follow symbolic links
MC_SYNC_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $MC_SYNC_DIR
cd ..

# Look for the clone McSync, create or clean it
if [ ! -d "${MC_SYNC_DIR}2" ]; then
    mkdir "${MC_SYNC_DIR}2"
else
    rm -r "${MC_SYNC_DIR}2"/*
fi

# Copy all the contents
cp -r $MC_SYNC_DIR/* "${MC_SYNC_DIR}2"