#!/bin/sh

# Important: Do not move this file out of the McSync root folder.

# compile.sh builds McSync, tags it with the current machine architecture and sets
# its "modified" timestamp to the one of the most recently changed source file.
# This timestamp is then used by mcsync.sh to identify whether source code has
# changed since the last build.

MACHINE_ARCHITECTURE=`cc -v 2>&1 | grep Target: | sed 's/.*: *//'`

echo "Creating executable mcsync.$MACHINE_ARCHITECTURE"

# Change into McSync root directory (the path of this script file)
cd "$( cd "$( dirname "$0" )" && pwd )"

cd source

cc -O -g -o ../bin/mcsync.$MACHINE_ARCHITECTURE -lncurses -Wall -I. engine/*.c tui/*.c

# Find the most recently modified source or header file
LATEST_FILE=`find .  \( -name "*.c" -o -name "*.h" \) -type f -exec stat -f "%m %N" {} \; \
            | sort -n | tail -1 | cut -f2- -d" "`

# Now set the timestamp of the executable to match the timestamp of the source.
touch -r $LATEST_FILE ../bin/mcsync.$MACHINE_ARCHITECTURE