#!/bin/csh

# This script helps to start McSync in slave mode when contacted over the
# network. Because McSync uses the invocation path to figure out where its
# log files are (./data/log), we need to cd into the root directory of McSync
# before invocation of the binary.

# we don't know what machine we are on or what directory we are in
# but $0 found us to invoke us, so it can help us find our files
# $0:h has the final path component stripped (unless there was nothing else)
# so the following gets us to our 'source' directory
if ( $0:h != $0 ) cd $0:h

bin/mcsync $*
